admin.username=${ADMIN_USERNAME}
admin.password.hash=${ADMIN_PASSWORD_HASH}
spring.datasource.url=jdbc:mysql://mysql.gip.superb.net:3306/shb6_313_1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.mail.host=smtp.superb.net
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=100MB